pipeline {
  agent any
  stages {
    stage('Info') {
      steps {
        sh "echo Job: ${env.JOB_NAME}"
        sh "echo Build: ${env.BUILD_NUMBER}"
      }
    }
    stage('Test') {
      agent {
        docker {
          image 'python:3.6-slim'
        }
      }
      steps {
        sh "pytest"
      }
    }
  }
}
