def runInDocker(String image, Closure body) {
  docker.image(image).inside {
    body()
  }
}

pipeline {
  agent any

  options {
    timestamps()
    disableConcurrentBuilds()
  }
  environment {
    IMAGE_NAME = "python-ci-tools:${env.BUILD_NUMBER}"
  }
  stages {
    stage('Info') {
      steps {
        sh "echo Job: ${env.JOB_NAME}"
        sh "echo Build: ${env.BUILD_NUMBER}"
      }
    }
    stage('CI - Lint') {
      steps {
        script {
          runInDocker('python:3.6-slim') {
            sh '''
                apt-get update && apt-get install -y make
                pip install --upgrade pip
                pip install -r requirements.txt flake8 mypy
                make lint
               '''
          }
        }
      }
    }
    stage('CI - Test') {
      steps {
        script {
          runInDocker('python:3.6-slim') {
            sh '''
                pip install --upgrade pip
                pip install -r requirements.txt
                pytest -q
               '''
          }
        }
      }
    }
    stage('CI - Build image') {
      steps {
        script {
            sh "echo IMAGE_NAME: ${env.IMAGE_NAME}"
            docker.build(env.IMAGE_NAME, "-f devops/Dockerfile .")
        }
      }
    }
    stage('CD') {
        steps {
            script {
                sh 'docker compose up -d'
                sh 'sleep 5'
                sh 'curl --fail http://localhost:5001'
            }
        }
        post {
            always {
                sh 'docker compose down --volumes || true'
                sh 'docker rmi IMAGE_NAME || true'
            }
            success {
                echo 'SUCCESS'
            }
            failure {
                echo 'FAILURE'
                sh 'docker compose logs || true'
            }
        }
    }
  }
}
