pipeline {
  agent any
  stages {
    stage('Info') {
      steps {
        sh "echo Job: ${env.JOB_NAME}"
        sh "echo Build: ${env.BUILD_NUMBER}"
      }
    }
    stage('Install') {
      agent {
        docker {
          image 'python:3.6-slim'
        }
      }
      steps {
        sh '''
            pip install -r requirements.txt flake8 mypy 
           '''
      }
    }
    stage('CI - Lint') {
      agent {
        docker {
          image 'python:3.6-slim'
        }
      }
      steps {
        sh '''
            make lint
           '''
      }
    }
    stage('CI - Test') {
      agent {
        docker {
          image 'python:3.6-slim'
        }
      }
      steps {
        sh '''
            pip install -r requirements.txt
            pytest
           '''
      }
    }
  }
}
